export type RailAvConfigType = {
    _id: string;
    reqEnqParam: string;
    __v: number;
    baseFare: string;
    bkgCfg: BookingConfig;
    cateringCharge: string;
    distance: string;
    dynamicFare: string;
    enqClass: string;
    from: string;
    ftBookingMsgFlag: string;
    fuelAmount: string;
    informationMessage: InformationMessage[];
    insuredPsgnCount: string;
    nextEnqDate: string;
    otherCharge: string;
    quota: string;
    rdsTxnPwdFlag: string;
    reservationCharge: string;
    serverId: string;
    serviceTax: string;
    superfastCharge: string;
    taRdsFlag: string;
    tatkalFare: string;
    timeStamp: string;
    to: string;
    totalConcession: string;
    totalFare: string;
    trainName: string;
    trainNo: string;
    trainsiteId: string;
    travelInsuranceCharge: string;
    travelInsuranceServiceTax: string;
    upiRdsFlag: string;
    wpServiceCharge: string;
    wpServiceTax: string;
};

export type BookingConfig = {
    seniorCitizenApplicable: string;
    foodChoiceEnabled: string;
    idRequired: string;
    bedRollFlagEnabled: string;
    maxMasterListPsgn: string;
    maxPassengers: string;
    maxInfants: string;
    minNameLength: string;
    maxNameLength: string;
    srctznAge: string;
    srctnwAge: string;
    maxARPDays: string;
    maxRetentionDays: string;
    minPassengerAge: string;
    maxPassengerAge: string;
    maxChildAge: string;
    minIdCardLength: string;
    maxIdCardLength: string;
    minPassportLength: string;
    maxPassportLength: string;
    srctzTAge: string;
    lowerBerthApplicable: string;
    newTimeTable: string;
    childBerthMandatory: string;
    validIdCardTypes: string[];
    applicableBerthTypes: string[];
    suvidhaTrain: string;
    specialTatkal: string;
    atasEnable: string;
    gatimaanTrain: string;
    foodDetails: any[]; // Adjust if food details have a specific type
    travelInsuranceEnabled: string;
    travelInsuranceFareMsg: string;
    uidVerificationPsgnInputFlag: string;
    uidVerificationMasterListFlag: string;
    uidMandatoryFlag: string;
    gstDetailInputFlag: string;
    gstinPattern: string;
    forgoConcession: string;
    twoSSReleaseFlag: string;
    beyondArpBooking: string;
    acuralBooking: string;
    redemptionBooking: string;
    trainsiteId: string;
    bonafideCountryList: string[];
    pmfInputEnable: string;
    pmfInputMandatory: string;
    pmfInputMaxLength: string;
    captureAddress: string;
    _id: string;
};

type InformationMessage = {
    message: string;
    popup: string;
    paramName: string;
};
